ChatConfig:
  #Logs Direct Messages in Console
  logMessages: true
  #Logs Group Messages in Console
  logGroupMessages: true
#Required, fill this out.
mysql:
  host: "localhost"
  username: "root"
  password: "squidlover"
  port: 3306
  database: "plugins"

#A lot of these values are similar to CivCraft/Citadel, keep that in mind.
reinforcements:
  #World for rein's to be enabled in.
  world: "Estra"
  # The max amount of reinforcements to keep loaded
  max_cache_size: 20000000
  # "Acid" blocking material
  acidblock_material: GOLD_BLOCK
  types:
    stone:
      health: 25
      material: STONE
      #Mins to full health
      mature: 5
    iron:
      health: 100
      material: IRON
      #Mins to full health
      mature: 15
    diamond:
      health: 300
      material: DIAMOND
      #Mins to full health
      mature: 30
  #Blocks that cannot be rein'd
  non-rein:
    - BEDROCK
    - ENDER_PORTAL_FRAME
    - SAPLING
    - LONG_GRASS
    - DEAD_BUSH
    - PISTON_EXTENSION
    - PISTON_MOVING_PIECE
    - RED_ROSE
    - YELLOW_FLOWER
    - BROWN_MUSHROOM
    - RED_MUSHROOM
    - TNT
    - CROPS
    - FIRE
    - SNOW
    - ICE
    - CACTUS
    - SUGAR_CANE_BLOCK
    - PORTAL
    - CAKE_BLOCK
    - PUMPKIN_STEM
    - MELON_STEM
    - VINE
    - NETHER_WARTS
    - ENDER_PORTAL

#Snitch implementation is just merely snitch "hits" at the start, not dealing with logsnitches until First Season probably.
snitches:
  #Radius of a snitch, results in a 23x23x23 box.
  defaultCubeSize: 11
  #Refresh immediately on a player who is on the group walking over it
  refreshImmediately: true
  #Sends a message if the snitch exists and a player who isn't on the group breaks it.
  #e.x. "[SNITCH] Owned by <Player> on <Group>"
  onBreakDisplayOwner: true
  snitchCull:
    enable: true
    #This is in days. (Default is just over weekly.)
    timeToCull: 8