name: EstraCore
description: Estra's primary core mechanic plugin.
main: net.estra.EstraCore.EstraCorePlugin
version: 1.0
authors: [Kayla]
website: estrapvp.net
depend: [CivModCore, Citadel]
commands:
  group:
    usage: "/group help"
    aliases: [g, f, faction]
    description: Allows you to modify groups.
  exit:
    usage: "/exit"
    aliases: [e, local, global]
    description: Exits whatever chat you are currently set to.
  msg:
    usage: "/msg <player> <optional: message>"
    aliases: [message, m, r, reply]
    description: Directly messages another player.